[project]
name = "donutdetailer"
description = ""
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/DonutsDelivery/ComfyUI-DonutDetailer"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-DonutDetailer"
Icon = ""
